Linear Regression (Supervised Machine Learning)

In [24]:
#Import Python Libraries
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [25]:
#Create a random 10 length array
array = np.array([1,2,3,4,5,6,7,8,9, 10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
#Reshap array 
new_array = array.reshape(-1,1)
print(new_array)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [27]:
#Create a ones array
ones_array = np.ones((10,1))
print(ones_array)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [28]:
#Combine both arrays (new_array and ones_array)
X = np.hstack((new_array, ones_array))
print(X)

[[ 1.  1.]
 [ 2.  1.]
 [ 3.  1.]
 [ 4.  1.]
 [ 5.  1.]
 [ 6.  1.]
 [ 7.  1.]
 [ 8.  1.]
 [ 9.  1.]
 [10.  1.]]


In [ ]:
#Convert combined array into dataframe (features, Inpute/Independent variables)
X_result = pd.DataFrame(X)
print(X_result)

      0    1
0   1.0  1.0
1   2.0  1.0
2   3.0  1.0
3   4.0  1.0
4   5.0  1.0
5   6.0  1.0
6   7.0  1.0
7   8.0  1.0
8   9.0  1.0
9  10.0  1.0
